### ISSUE TITLE
[teleMelody] Inference (EN): pattern is empty list. thus, ValueError: min() arg is an empty sequence.

### ISSUE THREAD

**Issue by plusoneee** [microsoft/muzic#49]
Hi,  I run the `inference/infer_en.py` with the test data (`data/en/test`). Here is the output of each variables: 

**beats**:  
```
0 0 0 1 1 1 2 [sep] 1 2 2 0 1 1 2 [sep]
```
**beats_label**:
```
[[0], [0], [0], [1], [1], [1], [2], [2], [1], [2], [2], [0], [1], [1], [2]]
```
**clean(syllables)**: 
```
.............
```
**tmp**: 
```
['.']
```
**pattern**:
```
[]
```
The following error occurred, Does anyone know how to fix it? 
```python
min_bar = min([i[0] for i in e])
ValueError: min() arg is an empty sequence.
```
--

### Update 
Maybe do not need `clean()` function when run `infer_en.py` ?

**Comment by backspacetg** [comment]
Thank you for you information! I also met this error and I think this error is caused by [this regexp](https://github.com/microsoft/muzic/blob/4ace7087c5a997b8f5a9dda5306296aabd7e520f/telemelody/inferrence/infer_en.py#L42)
where `re.sub(r'.{6} *', ".", word)` may intend to filter something like `......`, so changing it to `re.sub(r'\.{6} *', ".", word)` fixes this problem.
